import Foundation

enum LocalizedStrings {
    static func text(_ key: String, language: AppLanguage) -> String {
        let table = language == .simplifiedChinese ? zh : en
        return table[key] ?? en[key] ?? key
    }

    private static let en: [String: String] = [
        "app.loading": "Loading ChemVault",
        "app.loading.detail": "Preparing your native research workspace.",
        "app.error.title": "ChemVault is not ready",
        "app.error.message": "The native resource could not be prepared. Restart the app or rebuild the project.",
        "module.home.title": "Home",
        "module.home.description": "ChemVault native workspace overview.",
        "module.model.title": "Molecular Modelling",
        "module.model.description": "Search molecules, enter SMILES, preview structures and prepare modelling workflows.",
        "module.files.title": "Scientific File Storage",
        "module.files.description": "Organise research files, instrument outputs and project materials.",
        "module.docs.title": "Documentation",
        "module.docs.description": "Browse ChemVault documentation, workflow notes and developer references.",
        "module.extract.title": "AI Scientific Data Extraction",
        "module.extract.description": "Prepare papers, PDFs and instrument files for structured scientific extraction.",
        "module.mail.title": "ChemVault Mail",
        "module.mail.description": "Manage project communication and research correspondence.",
        "module.user.title": "Account & Permissions",
        "module.user.description": "Review demo account state, permissions and module access.",
        "module.notifications.title": "System Notification Center",
        "module.notifications.description": "Track extraction jobs, deployments and file-processing events.",
        "module.settings.title": "Settings",
        "module.settings.description": "Configure language, region detection, appearance and API endpoints.",
        "home.title": "ChemVault",
        "home.subtitle": "A scientific workspace for chemistry, molecular data and research workflows.",
        "home.intro": "ChemVault brings compound search, molecular modelling, scientific file storage, documentation, AI data extraction and research operations into a native Apple workspace.",
        "home.section.modules": "Native ChemVault modules",
        "home.section.platform": "Research operating layer",
        "home.platform.text": "The app is structured for future API integration while remaining useful as a native MVP: local module navigation, demo permissions, region-aware language selection and clear placeholders for production services.",
        "home.cta.model": "Open Molecular Workspace",
        "home.cta.docs": "Read Documentation",
        "model.smiles": "SMILES input",
        "model.smiles.placeholder": "Enter a SMILES string, e.g. CC(=O)OC1=CC=CC=C1C(=O)O",
        "model.search": "Search molecule",
        "model.search.placeholder": "Molecule name, identifier or formula",
        "model.draw": "Draw molecule",
        "model.periodic": "Periodic table",
        "model.preview.title": "Molecule preview",
        "model.preview.body": "A native molecular preview and modelling pipeline placeholder. Future versions can connect to RDKit, Open Babel or ChemVault model APIs.",
        "model.recent": "Recent molecules",
        "files.search.placeholder": "Search files, reports or instrument outputs",
        "files.upload": "Upload file",
        "files.recent": "Recent scientific files",
        "files.empty.title": "No matching files",
        "files.empty.body": "ChemVault Files is ready for future secure storage API integration.",
        "docs.search.placeholder": "Search documentation",
        "docs.categories": "Documentation categories",
        "docs.detail.placeholder": "This native document page is ready for Markdown or remote documentation sync.",
        "extract.upload": "Upload scientific document",
        "extract.type": "Extraction type",
        "extract.jobs": "Extraction jobs",
        "extract.results": "Structured result preview",
        "extract.paper": "Paper-to-database",
        "extract.lab": "Lab report parser",
        "extract.instrument": "Instrument file extraction",
        "mail.mailboxes": "Mailboxes",
        "mail.placeholder": "ChemVault Mail is reserved for project communication and research correspondence APIs.",
        "user.profile": "Demo profile",
        "user.permissions": "Permissions",
        "user.demo": "Demo Mode",
        "notifications.unread": "Unread",
        "notifications.all": "All notifications",
        "settings.language": "Language",
        "settings.languageAuto": "Auto",
        "settings.languageEnglish": "English",
        "settings.languageChinese": "Chinese",
        "settings.languageManualEnglish": "Manual language: English",
        "settings.languageManualChinese": "Manual language: Chinese",
        "settings.region": "Region detection",
        "settings.regionDetecting": "Detecting region",
        "settings.regionChina": "Detected mainland China. Chinese content is active.",
        "settings.regionInternational": "Detected international region or unavailable result. English content is active.",
        "settings.refreshRegion": "Refresh region",
        "settings.appearance": "Appearance",
        "settings.appearanceSystem": "System",
        "settings.appearanceLight": "Light",
        "settings.appearanceDark": "Dark",
        "settings.api": "API endpoint",
        "settings.about": "About ChemVault",
        "settings.about.body": "ChemVault is an independently developed academic technology initiative for chemistry, molecular data and scientific knowledge infrastructure.",
        "settings.privacy": "Privacy",
        "settings.privacy.body": "Region detection uses country-code lookup only. Manual language selection is stored locally.",
        "common.open": "Open",
        "common.status": "Status",
        "common.available": "Available",
        "common.search": "Search",
        "common.version": "Version",
        "common.locked": "Locked"
    ]

    private static let zh: [String: String] = [
        "app.loading": "正在加载 ChemVault",
        "app.loading.detail": "正在准备原生科研工作台。",
        "app.error.title": "ChemVault 尚未准备完成",
        "app.error.message": "原生资源无法准备。请重启 App 或重新构建项目。",
        "module.home.title": "首页",
        "module.home.description": "ChemVault 原生工作台概览。",
        "module.model.title": "分子建模",
        "module.model.description": "检索分子、输入 SMILES、预览结构并准备建模工作流。",
        "module.files.title": "科研文件存储",
        "module.files.description": "管理科研文件、仪器输出和项目材料。",
        "module.docs.title": "文档中心",
        "module.docs.description": "浏览 ChemVault 文档、工作流笔记和开发参考。",
        "module.extract.title": "AI 科学数据抽取",
        "module.extract.description": "准备论文、PDF 和仪器文件，用于结构化科研数据抽取。",
        "module.mail.title": "ChemVault 邮件",
        "module.mail.description": "管理项目沟通和科研协作邮件。",
        "module.user.title": "账户与权限",
        "module.user.description": "查看演示账户状态、权限和模块访问范围。",
        "module.notifications.title": "系统通知中心",
        "module.notifications.description": "跟踪抽取任务、部署完成和文件处理事件。",
        "module.settings.title": "设置",
        "module.settings.description": "配置语言、地区检测、外观和 API 地址。",
        "home.title": "ChemVault",
        "home.subtitle": "面向化学、分子数据与科研流程的科学工作台。",
        "home.intro": "ChemVault 将化合物检索、分子建模、科研文件存储、文档、AI 数据抽取和研究运营整合为 Apple 原生工作台。",
        "home.section.modules": "ChemVault 原生模块",
        "home.section.platform": "研究操作层",
        "home.platform.text": "App 以未来 API 接入为目标设计，同时作为原生 MVP 保持可用：本地模块导航、演示权限、基于地区的语言选择，以及面向生产服务的清晰占位。",
        "home.cta.model": "打开分子工作区",
        "home.cta.docs": "查看文档",
        "model.smiles": "SMILES 输入",
        "model.smiles.placeholder": "输入 SMILES，例如 CC(=O)OC1=CC=CC=C1C(=O)O",
        "model.search": "检索分子",
        "model.search.placeholder": "分子名称、标识符或分子式",
        "model.draw": "绘制分子",
        "model.periodic": "周期表",
        "model.preview.title": "分子预览",
        "model.preview.body": "这里是原生分子预览和建模流程占位。后续版本可以接入 RDKit、Open Babel 或 ChemVault model API。",
        "model.recent": "最近分子",
        "files.search.placeholder": "检索文件、报告或仪器输出",
        "files.upload": "上传文件",
        "files.recent": "最近科研文件",
        "files.empty.title": "没有匹配文件",
        "files.empty.body": "ChemVault Files 已为后续安全存储 API 接入预留。",
        "docs.search.placeholder": "搜索文档",
        "docs.categories": "文档分类",
        "docs.detail.placeholder": "该原生文档页已为 Markdown 或远程文档同步预留。",
        "extract.upload": "上传科学文档",
        "extract.type": "抽取类型",
        "extract.jobs": "抽取任务",
        "extract.results": "结构化结果预览",
        "extract.paper": "论文到数据库",
        "extract.lab": "实验报告解析",
        "extract.instrument": "仪器文件抽取",
        "mail.mailboxes": "邮箱",
        "mail.placeholder": "ChemVault Mail 为项目沟通和科研协作邮件 API 预留。",
        "user.profile": "演示资料",
        "user.permissions": "权限",
        "user.demo": "演示模式",
        "notifications.unread": "未读",
        "notifications.all": "全部通知",
        "settings.language": "语言",
        "settings.languageAuto": "自动",
        "settings.languageEnglish": "英语",
        "settings.languageChinese": "中文",
        "settings.languageManualEnglish": "手动语言：英语",
        "settings.languageManualChinese": "手动语言：中文",
        "settings.region": "地区检测",
        "settings.regionDetecting": "正在检测地区",
        "settings.regionChina": "检测到中国大陆地区，已启用中文内容。",
        "settings.regionInternational": "检测到国际地区或结果不可用，已启用英文内容。",
        "settings.refreshRegion": "刷新地区",
        "settings.appearance": "外观",
        "settings.appearanceSystem": "跟随系统",
        "settings.appearanceLight": "浅色",
        "settings.appearanceDark": "深色",
        "settings.api": "API 地址",
        "settings.about": "关于 ChemVault",
        "settings.about.body": "ChemVault 是一个独立开发、研究导向的学术技术项目，面向化学、分子数据和科学知识基础设施。",
        "settings.privacy": "隐私",
        "settings.privacy.body": "地区检测只使用国家代码查询。手动语言选择仅存储在本机。",
        "common.open": "打开",
        "common.status": "状态",
        "common.available": "可用",
        "common.search": "检索",
        "common.version": "版本",
        "common.locked": "受限"
    ]
}
