import Foundation

enum LocalizedStrings {
    static func text(_ key: String, language: AppLanguage) -> String {
        let table = language == .simplifiedChinese ? zh : en
        return table[key] ?? en[key] ?? key
    }

    private static let en: [String: String] = [
        "app.loading": "Loading ChemVault",
        "app.loading.detail": "Preparing your native research workspace.",
        "app.error.title": "ChemVault is not ready",
        "app.error.message": "The native resource could not be prepared. Restart the app or rebuild the project.",
        "module.home.title": "Home",
        "module.home.description": "Supporting workspace overview.",
        "module.model.title": "Compound Search",
        "module.model.description": "Search compounds by name, formula, identifier or SMILES and open structured ChemVault records.",
        "module.files.title": "Scientific File Storage",
        "module.files.description": "Organise research files, instrument outputs and project materials.",
        "module.docs.title": "Documentation",
        "module.docs.description": "Browse ChemVault documentation, workflow notes and developer references.",
        "module.extract.title": "AI Scientific Data Extraction",
        "module.extract.description": "Prepare papers, PDFs and instrument files for structured scientific extraction.",
        "module.mail.title": "ChemVault Mail",
        "module.mail.description": "Manage project communication and research correspondence.",
        "module.user.title": "Account & Permissions",
        "module.user.description": "Review demo account state, permissions and module access.",
        "module.notifications.title": "System Notification Center",
        "module.notifications.description": "Track extraction jobs, deployments and file-processing events.",
        "module.settings.title": "Settings",
        "module.settings.description": "Configure language, region detection, appearance and connection preferences.",
        "home.title": "ChemVault",
        "home.subtitle": "Compound search first, supporting research tools around it.",
        "home.intro": "ChemVault is centered on fast compound lookup. Documentation, files and extraction tools stay available as lightweight supporting spaces.",
        "home.section.modules": "Supporting modules",
        "home.section.platform": "App focus",
        "home.platform.text": "The main app workflow is compound search. Other areas are intentionally compact so they support, rather than compete with, chemical lookup.",
        "home.cta.model": "Open Compound Search",
        "home.cta.docs": "Read Documentation",
        "model.smiles": "SMILES input",
        "model.smiles.placeholder": "Enter a SMILES string, e.g. CC(=O)OC1=CC=CC=C1C(=O)O",
        "model.search": "Search compound",
        "model.search.placeholder": "Molecule name, identifier or formula",
        "model.draw": "Draw molecule",
        "model.periodic": "Periodic table",
        "model.preview.title": "Compound preview",
        "model.preview.body": "Selected ChemVault records show formula, domain, summary and tags for quick review.",
        "model.recent": "Recent compounds",
        "compound.hero.title": "Compound Search",
        "compound.hero.body": "Search ChemVault compound records by common name, formula, identifier or SMILES. Results stay useful offline with a local reference set.",
        "compound.hero.badge": "Primary app workflow",
        "compound.search.title": "Find a compound",
        "compound.search.placeholder": "Aspirin, caffeine, benzene, NaCl, C9H8O4...",
        "compound.clear": "Reset",
        "compound.examples": "Examples",
        "compound.status.featured": "Featured local compounds",
        "compound.status.local": "Local compound index",
        "compound.status.live": "ChemVault live compound index",
        "compound.status.offline": "Offline local compound index",
        "compound.error.localSuggestions": "No live match was returned; showing local compound suggestions.",
        "compound.error.offline": "Live search is unavailable. Local compound results are shown instead.",
        "compound.results.count": "results",
        "compound.results.title": "Search results",
        "compound.noResults.title": "No compound match",
        "compound.noResults.body": "Try a common name, formula, identifier or SMILES string.",
        "compound.detail.title": "Selected record",
        "compound.fact.formula": "Formula",
        "compound.fact.domain": "Domain",
        "compound.fact.type": "Type",
        "compound.supporting.title": "Supporting tools",
        "compound.supporting.body": "Documentation, files and extraction remain available as secondary spaces around the compound search workflow.",
        "files.search.placeholder": "Search files, reports or instrument outputs",
        "files.upload": "Upload file",
        "files.recent": "Recent scientific files",
        "files.empty.title": "No matching files",
        "files.empty.body": "No supporting files match this filter.",
        "docs.search.placeholder": "Search documentation",
        "docs.categories": "Documentation categories",
        "docs.detail.placeholder": "Concise reference notes for using ChemVault compound search and related records.",
        "extract.upload": "Upload scientific document",
        "extract.type": "Extraction type",
        "extract.jobs": "Extraction jobs",
        "extract.results": "Structured result preview",
        "extract.paper": "Paper-to-database",
        "extract.lab": "Lab report parser",
        "extract.instrument": "Instrument file extraction",
        "mail.mailboxes": "Mailboxes",
        "mail.placeholder": "ChemVault Mail is currently a secondary communication space.",
        "user.profile": "Demo profile",
        "user.permissions": "Permissions",
        "user.demo": "Demo Mode",
        "notifications.unread": "Unread",
        "notifications.all": "All notifications",
        "settings.language": "Language",
        "settings.languageAuto": "Auto",
        "settings.languageEnglish": "English",
        "settings.languageChinese": "Chinese",
        "settings.languageManualEnglish": "Manual language: English",
        "settings.languageManualChinese": "Manual language: Chinese",
        "settings.region": "Region detection",
        "settings.regionDetecting": "Detecting region",
        "settings.regionChina": "Detected mainland China. Chinese content is active.",
        "settings.regionInternational": "Detected international region or unavailable result. English content is active.",
        "settings.refreshRegion": "Refresh region",
        "settings.appearance": "Appearance",
        "settings.appearanceSystem": "System",
        "settings.appearanceLight": "Light",
        "settings.appearanceDark": "Dark",
        "settings.api": "ChemVault connection",
        "settings.about": "About ChemVault",
        "settings.about.body": "ChemVault is an independently developed academic technology initiative for chemistry, molecular data and scientific knowledge infrastructure.",
        "settings.privacy": "Privacy",
        "settings.privacy.body": "Region detection uses country-code lookup only. Manual language selection is stored locally.",
        "common.open": "Open",
        "common.status": "Status",
        "common.available": "Available",
        "common.search": "Search",
        "common.version": "Version",
        "common.locked": "Locked"
    ]

    private static let zh: [String: String] = [
        "app.loading": "正在加载 ChemVault",
        "app.loading.detail": "正在准备原生科研工作台。",
        "app.error.title": "ChemVault 尚未准备完成",
        "app.error.message": "原生资源无法准备。请重启 App 或重新构建项目。",
        "module.home.title": "首页",
        "module.home.description": "辅助工作台概览。",
        "module.model.title": "化合物检索",
        "module.model.description": "按名称、分子式、标识符或 SMILES 检索化合物，并打开结构化 ChemVault 记录。",
        "module.files.title": "科研文件存储",
        "module.files.description": "管理科研文件、仪器输出和项目材料。",
        "module.docs.title": "文档中心",
        "module.docs.description": "浏览 ChemVault 文档、工作流笔记和开发参考。",
        "module.extract.title": "AI 科学数据抽取",
        "module.extract.description": "准备论文、PDF 和仪器文件，用于结构化科研数据抽取。",
        "module.mail.title": "ChemVault 邮件",
        "module.mail.description": "管理项目沟通和科研协作邮件。",
        "module.user.title": "账户与权限",
        "module.user.description": "查看演示账户状态、权限和模块访问范围。",
        "module.notifications.title": "系统通知中心",
        "module.notifications.description": "跟踪抽取任务、部署完成和文件处理事件。",
        "module.settings.title": "设置",
        "module.settings.description": "配置语言、地区检测、外观和连接偏好。",
        "home.title": "ChemVault",
        "home.subtitle": "以化合物检索为主，周边保留轻量科研工具。",
        "home.intro": "ChemVault 以快速化合物查询为核心。文档、文件和抽取工具作为辅助空间保留。",
        "home.section.modules": "辅助模块",
        "home.section.platform": "App 重点",
        "home.platform.text": "当前 App 的主流程是化合物检索，其它区域保持紧凑，只为查询流程提供辅助。",
        "home.cta.model": "打开化合物检索",
        "home.cta.docs": "查看文档",
        "model.smiles": "SMILES 输入",
        "model.smiles.placeholder": "输入 SMILES，例如 CC(=O)OC1=CC=CC=C1C(=O)O",
        "model.search": "检索化合物",
        "model.search.placeholder": "分子名称、标识符或分子式",
        "model.draw": "绘制分子",
        "model.periodic": "周期表",
        "model.preview.title": "化合物预览",
        "model.preview.body": "选中的 ChemVault 记录会展示分子式、领域、摘要和标签，便于快速检查。",
        "model.recent": "最近化合物",
        "compound.hero.title": "化合物检索",
        "compound.hero.body": "按常用名、分子式、标识符或 SMILES 检索 ChemVault 化合物记录。离线时也会显示本地参考结果。",
        "compound.hero.badge": "App 主流程",
        "compound.search.title": "查找化合物",
        "compound.search.placeholder": "阿司匹林、咖啡因、苯、NaCl、C9H8O4...",
        "compound.clear": "重置",
        "compound.examples": "示例",
        "compound.status.featured": "本地精选化合物",
        "compound.status.local": "本地化合物索引",
        "compound.status.live": "ChemVault 在线化合物索引",
        "compound.status.offline": "离线本地化合物索引",
        "compound.error.localSuggestions": "在线结果没有匹配项，已显示本地化合物建议。",
        "compound.error.offline": "在线检索暂不可用，当前显示本地化合物结果。",
        "compound.results.count": "条结果",
        "compound.results.title": "检索结果",
        "compound.noResults.title": "没有匹配的化合物",
        "compound.noResults.body": "请尝试常用名、分子式、标识符或 SMILES。",
        "compound.detail.title": "选中记录",
        "compound.fact.formula": "分子式",
        "compound.fact.domain": "领域",
        "compound.fact.type": "类型",
        "compound.supporting.title": "辅助工具",
        "compound.supporting.body": "文档、文件和抽取功能作为化合物检索流程周边的辅助空间保留。",
        "files.search.placeholder": "检索文件、报告或仪器输出",
        "files.upload": "上传文件",
        "files.recent": "最近科研文件",
        "files.empty.title": "没有匹配文件",
        "files.empty.body": "没有匹配该筛选条件的辅助文件。",
        "docs.search.placeholder": "搜索文档",
        "docs.categories": "文档分类",
        "docs.detail.placeholder": "用于说明 ChemVault 化合物检索和相关记录的简明参考说明。",
        "extract.upload": "上传科学文档",
        "extract.type": "抽取类型",
        "extract.jobs": "抽取任务",
        "extract.results": "结构化结果预览",
        "extract.paper": "论文到数据库",
        "extract.lab": "实验报告解析",
        "extract.instrument": "仪器文件抽取",
        "mail.mailboxes": "邮箱",
        "mail.placeholder": "ChemVault 邮件目前作为辅助沟通空间保留。",
        "user.profile": "演示资料",
        "user.permissions": "权限",
        "user.demo": "演示模式",
        "notifications.unread": "未读",
        "notifications.all": "全部通知",
        "settings.language": "语言",
        "settings.languageAuto": "自动",
        "settings.languageEnglish": "英语",
        "settings.languageChinese": "中文",
        "settings.languageManualEnglish": "手动语言：英语",
        "settings.languageManualChinese": "手动语言：中文",
        "settings.region": "地区检测",
        "settings.regionDetecting": "正在检测地区",
        "settings.regionChina": "检测到中国大陆地区，已启用中文内容。",
        "settings.regionInternational": "检测到国际地区或结果不可用，已启用英文内容。",
        "settings.refreshRegion": "刷新地区",
        "settings.appearance": "外观",
        "settings.appearanceSystem": "跟随系统",
        "settings.appearanceLight": "浅色",
        "settings.appearanceDark": "深色",
        "settings.api": "ChemVault 连接",
        "settings.about": "关于 ChemVault",
        "settings.about.body": "ChemVault 是一个独立开发、研究导向的学术技术项目，面向化学、分子数据和科学知识基础设施。",
        "settings.privacy": "隐私",
        "settings.privacy.body": "地区检测只使用国家代码查询。手动语言选择仅存储在本机。",
        "common.open": "打开",
        "common.status": "状态",
        "common.available": "可用",
        "common.search": "检索",
        "common.version": "版本",
        "common.locked": "受限"
    ]
}
